### PR TITLE
Add a kickstart template

### PR DESCRIPTION
**Pull request by chevdor**
This PR will only works once merged into master.

To test however, you can run locally:

     kickstart .

After you answered all the questions, you will find your new file under: `{{category}}/{{name}}.toml`

### CODE REVIEW

**Comment by stiiifff** [comment]
Awesome ! Thank you so much for this.
The field for categories is `categories`.

**Comment by chevdor** [comment]
> The field for categories is categories.

Are you suggesting a change? Not sure what you mean :)

**Comment by stiiifff** [comment]
@chevdor Yes, sorry if I wasn't clear: `category` should be `categories`. thx !

**Comment by chevdor** [comment]
I still don't get it sorry. If you mean that we can have several categories, since I am currently using THE category as folder name, a simple `s/category/categories/` will not work.

**Comment by chevdor** [comment]
Or do you want an additiionnal `categories` field in addition to `category` ?

**Comment by stiiifff** [comment]
The job that's importing the files from this repo will take the top-level folder name as category, plus, if there is a `categories` field defined (which is an array of strings), the content of that field will be merged with the "folder-name-as-category". So the `category` field will not be recognized, it should be named `categories`. Hope that makes sense.

**Review by stiiifff — APPROVED** [review]

**Comment by stiiifff** [comment]
Thx !

**Comment by chevdor** [comment]
I find the process rather weird but I think I got what you expect and added it in the latest commit.

NOTE: If the user provides (note the extra spaces) `aa, bb,cc ,dd` it will be added as `["aa", " bb", "cc ", "dd"]`

**Comment by stiiifff** [comment]
Let's see how it goes, if it's causing issues, I'll adapt the job that's syncing the data.

**Comment by chevdor** [comment]
We can also probably cleanup in the template but that means adding an extra loop (there is a `map` function that could have been helpful but it does not work in that case)... possible if that really happends often.

**Pull request merged**
